### PR TITLE
Xml parser

### PR DESCRIPTION
**Pull request by tminussi**
Hello, Pedro.

I have gone ahead and created a PR for the issue  #20 

Hope you like it and approve the PR.

Thanks,

Thales

### CODE REVIEW

**Comment by Pedro12909** [comment]
Hi @tminussi 
Thanks for contributing to RexCord. We're happy you submitted a PR this fast, but it appears that there are some issues in your code, according to Travis. Check the build logs and see what's going on. (Hint: checkstyle)

Please do `mvn verify` before submitting your code. Don't commit unless the build passes. I'm going to close this PR. Fix build problems and then create another PR

Any questions, feel free to come to our Discord Server! :)

**Comment by tminussi** [comment]
Yes, I realized it when I ran mvn verify, but I didn't have time to fix the things Travis was not happy about. 

However, I would like to point that I do not agree with some of your Travis config. 80 characters may be too short for a line (in our case, it complains about a method on the parser. Now, if you consider private <T> static T {methodName} ({Method parameters} it is more than acceptable to have more than 80 characters. I think it hits 83 in our case). Another thing is that it is complaining about brackets not being whitespaced. This is due to a private constructor to prevent the class from being instantiated. I will open a new PR when build passes (should do it by Sunday, will be pretty busy by today and tomorrow), but I think you should review some of Travis's rules.

Thank you! Looking forward to getting this issue done as soon as possible :)

**Comment by Pedro12909** [comment]
I agree that line length could be a little bit more, ill probably tweak it in the future. Regarding whitespaces, these checks are there to make code more readable. It doesn't have anything to do with what goes inside constructors and methods. Take a read at checkstyle's documentation to see what i'm talking about :)

**Comment by tminussi** [comment]
Ye, no problem. Its just that the constructor looks like this: private {SomeClass} () {}
But no worries, I will fix it by sunday and you will have this functionally working fine.

Thanks for letting me contribute to it :)

**Comment by Pedro12909** [comment]
in that case, to fix the checkstyle error, change the constructor to this:
```
private Foo() {
}
```

notice the whitespace before the `()` and after `()` ? That was the problem

**Pull request closed without merging**
