### PR TITLE
XML Parser

### PR DESCRIPTION
**Pull request by tminussi**
Added a class responsible for parsing a XML file into a Pojo.

### CODE REVIEW

**Comment by tminussi** [comment]
Awesome. Thanks, @freitzzz

**Comment by tminussi** [comment]
Alright, I have just done what you said. Please check if it matches what you asked accordingly.

Thanks!

**Comment by Pedro12909** [comment]
@tminussi I noticed some minor things that need to be changed before merging:

* in .gitignore, config.xml should be ignored, not example_config.xml (you want users to have access to our template, not the actual config file)

* change the values inside the example config to null, like this:

```xml
<config>
    <token>123</token>
    <prefix>123</prefix>
    <bannedCommands>DEFAULT</bannedCommands>
    <listenChannels>
        <listenChannel>50</listenChannel>
        <listenChannel>60</listenChannel>
        <listenChannel>70</listenChannel>
    </listenChannels>
    <apiGiphyKey>33a79488-c78c-448b-9c67-5723879e055e</apiGiphyKey>
</config>
```

**Comment by tminussi** [comment]
Can you provide the comments on the XML yourself? I'm not into your business rules, so my comments would probably make no sense.

**Comment by Pedro12909** [comment]
Sure, I'll add them later!

**Comment by tminussi** [comment]
Thanks.

Also, are you sure listenChannels are not being read from the file? There's a unit test that guarantees this. I have just double checked and it seems to work fine.

**Comment by tminussi** [comment]
image

here is a screenshot showing that listenChannels are being read correctly.

**Comment by Pedro12909** [comment]
Just found the problem! Change all the `else if()` conditions to `if()` in the `readFile()` method. At runtime, only the first if was being reached, that's why banned commands and listen channels were not being set  properly (they were being read, but not assigned to RexCord's class).

**Comment by tminussi** [comment]
When I quickly read over your code I didn't see there was a specific method for reading listenChannels. I thought they were all in the switch clause. Now, re-reading the code I see listenChannels was completely separate. The else if structure was created to simulate your switch, since whenever it hit a "case" condition, it would execute the statement and then break from it.

Changing to new IF structure will solve the problem.

image

Here is a screenshot with the values set on rexCord object.

**Comment by Pedro12909** [comment]
Yup, that's it! :)

**Pull request merged**
