### PR TITLE
Format Bot Messages #40

### PR DESCRIPTION
**Pull request by beatyt**
Hi,

I believe I have a basic version of this.. I'm not what all behavior it should have.  Plus idk if an object encapsulating the message is good or if someone has a better way in mind.

Would be more than happy to hear feedback and change things. 😄 

---

Issues I encountered while doing this:

    example_config tells people to rename to "config.txt"

 should be config.cfg

     <property name="lineSeparator" value="lf"/>

I did not include this in the commit but I had errors due to the LFs. Adding that line fixed the linter for me.

    title cannot be null or empty in an embedded message

I added some dumby text.

### CODE REVIEW

**Comment by Pedro12909** [comment]
Hi @beatyt, thanks for contributing to RexCord. After thinking about it, some messages should be embedded and others not. `greet` is an example of a command that should not use embedded messages, for example.

Create a separate method to facilitate sending messages with embedded content. Then, format these commands so that RexCord sends their output in an embedded message:

* about

* info

* joke

* gif

PS.: Feel free to add those issues you found in our issues page. As soon as I tag them as accepted, you can start working on them :)

**Comment by beatyt** [comment]
Hi,

I think the TravisCI build failed to download a dependency?

- direct messages to the bot stopped working
- the markdown image previews do not render unless they are sent as images in the EmbeddedObject using `builder.withImage`

**Comment by Pedro12909** [comment]
Hi @beatyt . Try running `mvn clean install` locally and then `mvn verify` and check if the build passes.

**Comment by beatyt** [comment]
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.227 s
[INFO] Finished at: 2017-10-03T18:58:39-04:00
[INFO] Final Memory: 29M/310M
[INFO] ------------------------------------------------------------------------
```
and
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.611 s
[INFO] Finished at: 2017-10-03T18:58:45-04:00
[INFO] Final Memory: 20M/305M
[INFO] ------------------------------------------------------------------------
```

The travis-ci error is:

```
 Failed to transfer file: https://repo.maven.apache.org/maven2/org/apache/maven/maven-archiver/3.1.1/maven-archiver-3.1.1.jar. Return code is: 503 , ReasonPhrase:first byte timeout.
```

Any way to kick off a new build to see?

**Pull request merged**
