### PR TITLE
#56 Added unit tests for commands

### PR DESCRIPTION
**Pull request by GaruGaru**
- Added unit tests for commands
- Added mockito dependency
- Fixed reminder command bug
- Removed final modifier from RexCord class in order to make it mockable/extendable 

Still missing tests for some commands for the following reasons: 
- Remote call (require wiremock or similar mocking framework)
- System exit call (need to catch the exit call or don't call it if in testing env.)

### CODE REVIEW

**Comment by GaruGaru** [comment]
Looks like the tests are passing but the build fails because checkstyle doesn't allow the RexCord class to be extendable ,but in order to test it you have to mock / extend it or just create an interface between the commands and the real object

**Comment by tumit** [comment]
@GaruGaru  I want to help to write unit testing for this project and now I use PowerMockito to mock final class and static class it work properly :)

details: https://www.codeproject.com/Articles/806508/Using-PowerMockito-to-Mock-Final-and-Static-Method

**Comment by GaruGaru** [comment]
Hey @tumit  looks nice ! That library definitely solves the final classes problem. Thank you very much for the effort and for the docs :+1:  i'll  update the pull request using the library you proposted  asap

**Comment by Pedro12909** [comment]
Hi @GaruGaru  Thanks for your contribution. Your work looks good. However, just for the record, make sure that you create a PR to our dev branch instead of master. This ensures master is always stable and working. Since this is not really a feature but some UTs, im going to open an exception and accept it :)

**Pull request merged**
